### ISSUE TITLE
Who is cuty?

### ISSUE THREAD

**Issue by valkjsaaa** [liudangyi/500px-wallpaper#1]
I though it should be @liudangyi ? If it is, please fix it.

**Comment by liudangyi** [comment]
cuty is a virtual user on the server.

**Comment by valkjsaaa** [comment]
Yeah. I thought you can set all the history about cuty to you account?

**Comment by valkjsaaa** [comment]
like this: http://serverfault.com/questions/12373/how-do-i-edit-gits-history-to-correct-an-incorrect-email-address-name
